### ISSUE TITLE
Seems impossible to import RSA key pairs and public keys generated outside PCL Crypto

### ISSUE THREAD

**Issue by PinoEire** [AArnott/PCLCrypto#104]
This in any flavour gives a format exception:

            byte[] keyBytes = null;
            ICryptographicKey key;
            IAsymmetricKeyAlgorithmProvider rsa = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
              keyBytes = Convert.FromBase64String(myKey);
            key = rsa.ImportKeyPair(keyBytes);

**Comment by AArnott** [comment]
There are several formats for key pairs and public keys. When you call `ImportKeyPair`, specify the format that you exported from another library. Please let me know if that doesn't work for you.

**Comment by PinoEire** [comment]
@AArnott As I specified, it does not work: I tried keys generated from from both Puttygen and OpenSSH and none works. If you think it works, can you please post an example?

**Comment by AArnott** [comment]
@PinoEire your code sample doesn't show what I am asking you to try. 

But now that you mention puttygen and OpenSSH, what I've observed is they tend to export their keys as ASCII text rather than any of the four binary key formats supported by .NET, WinRT, or (in particular) this library. The supported formats are in the enum that is the second parameter of the `ImportKeyPair` method, and you can [refer to source code](https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Shared.Formatters/Formatters/KeyFormatter.cs#L70) if you like.
