### ISSUE TITLE
iOS Unified

### ISSUE THREAD

**Issue by paylocity-blackcobra** [AArnott/PCLCrypto#11]
Any thoughts on adding support for iOS Unified? Getting a Not implemented in reference assembly right now. Using latest nuget version 0.5.2.14286

**Comment by AArnott** [comment]
Upgrade to 1.0.0-beta2 and let me know if it works for you.

**Comment by trik** [comment]
it's working for me with unified apis Xamarin.iOS 8.6.3.3, manually adding a reference to Mono.Security (not the nuget package)

**Comment by AArnott** [comment]
Great. I'll republish 1.0.0 as a stable package. If I have time I'll also
see if the requirement on a newer version of NuGet is actually legit or if
I can roll that requirement back.

**Comment by AArnott** [comment]
Fixed by 7230469c7815f80d726f00081509ab1a92f6b75d

**Comment by gautambjain** [comment]
Thanks Andrew for adding support for Unified API.

PCL Crypto requires Nuget 2.8.3.

However, I am unable to include PCL Crypto project to Xamarin.iOS project because Xamarin Studio ships Nuget 2.8.1.

So we are stuck here. The below thread discusses this issue including discussions related to PCL Crypto. They have a workaround for Windows version. But not the Mac Xamarin Studio.

https://forums.xamarin.com/discussion/29754/can-i-update-the-nuget-core-dll-used-by-xamarin-studio

Is it possible that PCL Crypto's can use an older version of Nuget?

Or is there any other workaround?

**Comment by trik** [comment]
you can manually install the nuget package using version 2.8.3 outside xamarin studio and then add reference to the library

**Comment by AArnott** [comment]
See #13 for a discussion about the NuGet Client 2.8.3 issue.

**Comment by gautambjain** [comment]
Great! Thanks trik & Andrew for the workarounds!
