### ISSUE TITLE
(Question)(iOS) Is it possible to decrypt RSA with only "Modulus" and "D" parameters?

### ISSUE THREAD

**Issue by y2k** [AArnott/PCLCrypto#113]
By the algorithm "modulus" and "d" enough for decryption 
https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsaparameters(v=vs.110).aspx#Remarks (Remarks)

I create this code and it works on Android, but on iOS it throw exception "status was -9809".
I need help - maybe I do something wrong, maybe it's impossible at all?
```
public byte[] DecryptRsa(byte[] data, byte[] modulus, byte[] d)
{
    var param = new RSAParameters
    {
        Modulus = modulus,
        D = d,

        // Stupid workaround to avoid crash on Android on call "ImportParameters()"
        Exponent = new byte[1],
        DP = new byte[1],
        DQ = new byte[1],
        InverseQ = new byte[1],
        P = new byte[1],
        Q = new byte[1],
    };

    var alg = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
    using (var key = alg.ImportParameters(param))
        return CryptographicEngine.Decrypt(key, data);
}
```

**Comment by AArnott** [comment]
While it may be possible to decrypt with only modulus and D (because the other parameters can be derived from them), evidently Android is willing to do the derivation for you and iOS isn't. PCLCrypto will not do this for you because it does not implement crypto itself. So if you want to do this, you'll have to do it yourself, I guess.
