### ISSUE TITLE
Rsa with no padding?

### ISSUE THREAD

**Issue by SuhanKoh** [AArnott/PCLCrypto#114]
Hi, will this library support RSA encryption with custom/no padding feature in the future?

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
