### ISSUE TITLE
Trying to get RsaPkcs1 to work on both xamarin forms UWP and Azure server

### ISSUE THREAD

**Issue by ozzy1873** [AArnott/PCLCrypto#117]
I am having trouble encrypting on Xamarin forms UWP with a public key generated on Azure server. This works great if all the encryption/decryption is done only on one platform or the other, but the keys do not seem to work cross platform. The code below runs without error. However, it fails when I encrypt using the public key of the server with the error:

The parameter is incorrect (SECURITY_STATUS error: NTE_INVALID_PARAMETER (0x80090027))

Stack trace:
 at PInvoke.NCrypt.NCryptEncrypt(SafeKeyHandle key, Byte[] plaintext, Void* paddingInfo, NCryptEncryptFlags flags)
   at PCLCrypto.NCryptAsymmetricKey.<>c__DisplayClass24_0.<Encrypt>b__0(Void* padding, NCryptEncryptFlags flags)
   at PCLCrypto.NCryptAsymmetricKey.EncryptOrDecrypt(EncryptOrDecryptFunction cipherFunction)
   at MyApp.Crypto.Encrypt(String plainString)

Am I doing something wrong?

```csharp
        private static string _serverPrivateKey;
        private static string _serverPublicKeyString;

        static void Main(string[] args)
        {
            CreateKey();

            var encrypted = Encrypt("This is a test");
            Console.WriteLine(encrypted);
            Console.WriteLine(Decrypt(encrypted));

            Console.ReadKey();
        }

        public static void CreateKey()
        {
            var asym = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
            var key = asym.CreateKeyPair(1024);
            var publicKey = key.ExportPublicKey(CryptographicPublicKeyBlobType.Pkcs1RsaPublicKey);
            _serverPublicKeyString = Convert.ToBase64String(publicKey);
            var Key = key.Export(CryptographicPrivateKeyBlobType.Pkcs1RsaPrivateKey);
            _serverPrivateKey = Convert.ToBase64String(Key);
        }

        public static string Encrypt(string plainString)
        {
            var encryptedString = string.Empty;

            try
            {
                var asym = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
                var plain = Encoding.UTF8.GetBytes(plainString);
                var pubKeyBytes = Convert.FromBase64String(_serverPublicKeyString);
                var pubKey = asym.ImportPublicKey(pubKeyBytes, CryptographicPublicKeyBlobType.Pkcs1RsaPublicKey);
                var encrypted = CryptographicEngine.Encrypt(pubKey, plain);
                encryptedString = Convert.ToBase64String(encrypted);
            }
            catch (Exception ex)
            {
            }

            return encryptedString;
        }

        public static string Decrypt(string encryptedString)
        {
            var decryptedString = string.Empty;

            try
            {
                var asym = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
                var privateKeyBytes = Convert.FromBase64String(_serverPrivateKey);
                var privateKey = asym.ImportKeyPair(privateKeyBytes, CryptographicPrivateKeyBlobType.Pkcs1RsaPrivateKey);
                var encrypted = Convert.FromBase64String(encryptedString);
                var decrypted = CryptographicEngine.Decrypt(privateKey, encrypted);
                decryptedString = Encoding.UTF8.GetString(decrypted, 0, decrypted.Length);
            }
            catch (Exception ex)
            {
            }

            return decryptedString;
        }
```

**Comment by AArnott** [comment]
We have in the past had to do careful key serialization for interop across platforms. But I think we've got that all taken care of. Particularly between Azure and UWP, I would expect since they're both Windows based that there wouldn't be any interop problems.

What I do notice though in your sample is that you seem to think RSA keys are for encrypting data. They are not. And if the data is more than just a very short array you'll get an error perhaps like what you're getting now. So my guess is when it doesn't work, it's because your data is too large rather than due to which platform created the key.

RSA encryption (as is true for any asymmetric encryption) is for encrypting symmetric keys. Then you use the symmetric key to encrypt the data. This ensures the data to be asymmetrically encrypted has a constant (and very short) length, and a performant solution since asymmetric encryption is _very slow_ so you don't want to encrypt more than a small symmetric key with it anyway.

**Comment by ozzy1873** [comment]
Ah, thank you for that thorough explanation. That is probably exactly the problem.
