### ISSUE TITLE
Xamarin.Mac support

### ISSUE THREAD

**Issue by tofutim** [AArnott/PCLCrypto#118]
Hi, I would like to add PCLCrypto to a Xamarin.Mac project. When I try to do so, I get

> Could not install package 'PInvoke.NCrypt 0.3.2'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any chance of getting it to work?

**Comment by AArnott** [comment]
I'd like to see that work. But IIRC Xamarin.Mac was a whole thing of its own (not like iOS). I can't remember specifics but I got the idea that it would be a massive amount of work to support it. Since netstandard comes with crypto APIs of its own, are those an option for you? PCLCrypto, if it supported your scenario, would allow you to write crypto to more than just the netstandard platforms, but for the amount of work it would be to support that, I'm not sure it's worth it if netstandard alone is sufficient for you.

**Comment by tofutim** [comment]
Good point, I'll try it.

**Comment by AArnott** [comment]
Xamarin.mac support will require a new special project in PCLCrypto to support that platform and _I think_ it must be built on a mac to work (which is super lame, but perhaps inevitable). I don't have time to add Xamarin.mac support in the next month so I hope the workaround for you works.

**Comment by tofutim** [comment]
I'm using netstandard11 - and System.Security.Cryptography is missing. :(

**Comment by AArnott** [comment]
You'd need a newer netstandard. Yes, PCLCrypto's value is in support for these "older" platforms. Unfortunately, Xamarin.Mac isn't one of them. And may never be -- it's undecided.

**Comment by tofutim** [comment]
A couple gotchas, but I was able to get it to work using netstandard13. Had to install System.Security.Cryptography.Algorithms nuget into .NET 4.6 project. Means we have to go from 4.5 to 4.6 though.

**Comment by AArnott** [comment]
cool.

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
