### ISSUE TITLE
iOS Only Supports SHA1 with OAEP Padding

### ISSUE THREAD

**Issue by kspearrin** [AArnott/PCLCrypto#124]
If you try any other digest, such as SHA256 you get a "status was '[Param](https://developer.apple.com/reference/security/errsecparam)'" exception when decrypting.

Related: http://stackoverflow.com/questions/28724696/ios-seckeyencrypt-oaep-sha512

You should probably update the docs to reflect this.

**Comment by AArnott** [comment]
We do have documentation platform support [here](https://github.com/AArnott/PCLCrypto/wiki/Algorithms-X-platforms-support#hash-algorithms). It might be buggy though.

**Comment by AArnott** [comment]
Note to self: when investigating this, refer to the details [here](https://gitter.im/AArnott/PCLCrypto?at=58fa265ec1d3b5015408bdb1)

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
