### ISSUE TITLE
System.Security.SecureString equivalent in PCLCrypto not found 

### ISSUE THREAD

**Issue by Duraiamuthan** [AArnott/PCLCrypto#126]
System.Security.SecureString is not supported in PCL I was hoping PCLCrypto would be providing that but I couldn't find the equivalent in PCLCrypto sofar ?

**Comment by AArnott** [comment]
You are correct: PCLCrypto doesn't carry this type. It looks like we could add a facade for it though as [it appears in nearly every platform](https://apisof.net/catalog/System.Security.SecureString).

But netstandard2.0 will include it as well, just FYI.

**Comment by Duraiamuthan** [comment]
@AArnott  Yes you are right 👍

**Comment by Duraiamuthan** [comment]
System.Security.SecureString is not compatible in PCL though so I am wondering how will you add a facade for that ? will u use dependency injection or something ?

**Comment by AArnott** [comment]
The same way everything else in PCLCrypto works: we define our own type for SecureString, and then based on the platform the app is actually running on, we have code to invoke into the platform. It's called the "PCL bait and switch trick".

**Comment by Duraiamuthan** [comment]
@AArnott Thanks for letting me know 🥇

**Comment by Duraiamuthan** [comment]
@AArnott I am curious when can I expect this feature from you ?

**Comment by AArnott** [comment]
I'm sorry to miscommunicate. I have no intention of adding SecureString myself. I tagged this issue as "up for grabs" to communicate this. I don't object to it being added, but since netstandard2.0 includes it, and it isn't necessary for any crypto APIs in PCLCrypto, I'm not going to spend time adding it myself. I just don't have enough time.
