### ISSUE TITLE
Xamarin.Android - App crashes when MainActivity inherits from FormsAppCompatActivity

### ISSUE THREAD

**Issue by ronakvala** [AArnott/PCLCrypto#128]
I was trying to implement PCLCrypto to my Xamarin.Forms project which has Xamarin.Droid and Xamarin.iOS support.

At first, I couldn't identify what's going wrong as it was just crashing app from MainActivity then I compared the difference in Sample example of PCLCrypto and my MainActivity file and the only difference I could find was the FormsApplicationActivity vs FormsAppCompatActivity.

In my Android project I use FormsAppCompatActivity instead of FormsApplicationActivity and I would like to keep it that way.

Is this something someone ever come across?

Thoughts?

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
