### ISSUE TITLE
SecItemAdd return -25308

### ISSUE THREAD

**Issue by rmenezes** [AArnott/PCLCrypto#133]
Hi,

I'm having the following exception when try to crypt some data when my iOS screen is locked:

``
 System.InvalidOperationException: SecItemAdd return -25308
  at PCLCrypto.RsaAsymmetricKeyAlgorithmProvider.ImportPublicKey (System.Byte[] keyBlob, PCLCrypto.CryptographicPublicKeyBlobType blobType) [0x000b4] in <0d3c0b2586f645d4a87ef50f78aa84f8>:0 
``

This only happens when the screen is locked, if I unlock the data is crypted normaly. 
I'm testing on iPhone 5C with iOS 10.3.2. The Entitlements.plist is already added.

Any ideias?

Tks

**Comment by pedrofcj** [comment]
+1 for this issue.

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
