### ISSUE TITLE
SecItemAdd returns -50 when importing public key

### ISSUE THREAD

**Issue by chao-master** [AArnott/PCLCrypto#136]
Code snippet:
```
var algo = WinRTCrypto.AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
RSAParameters rpar = new RSAParameters
{
    Exponent = Convert.FromBase64String(key.Exponent),
    Modulus = Convert.FromBase64String(key.Modulus)
};
_rsaKey = algo.ImportParameters(rpar);
```
When ran on iOS (emulator) results in an Error of "-50" from SecItemAdd

**Comment by wickedw** [comment]
FYI, 

I am seeing same error for code like so -

```
byte[] keyMaterial = pem.Decoded;
byte[] data = Encoding.UTF8.GetBytes(target);

var provider = PCLCrypto.WinRTCrypto.AsymmetricKeyAlgorithmProvider.OpenAlgorithm(PCLCrypto.AsymmetricAlgorithm.RsaPkcs1);
var publicKey = provider.ImportPublicKey(keyMaterial);

```
Not sure if this is related.

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
