### ISSUE TITLE
Linux mono support

### ISSUE THREAD

**Issue by mcmillab** [AArnott/PCLCrypto#145]
In a c# application of mine, this runs fine on Windows.
However when I attempt to run it on Linux using Mono I get this error:

>System.DllNotFoundException: NCrypt
>at (wrapper managed-to-native) PInvoke.NCrypt.NCryptOpenStorageProvider(PInvoke.NCrypt/SafeProviderHandle&,string,PInvoke.NCrypt/NCryptOpenStorageProviderFlags)
> at PInvoke.NCrypt.NCryptOpenStorageProvider (System.String providerName, PInvoke.NCrypt+NCryptOpenStorageProviderFlags flags) [0x00000]
> at PCLCrypto.NCryptAsymmetricKeyProviderBase.ImportPublicKey (System.Byte[] keyBlob, PCLCrypto.CryptographicPublicKeyBlobType blobType)`

This is called via:

`var rsa = WinRTCrypto.AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);`

Should it work on Mono?

**Comment by AArnott** [comment]
Which version are you using? If you're using the 2.x versions, I suppose I don't expect this to work because I made some significant reliability and perf fixes that make the "desktop" version call into win32 dll's directly, which mono doesn't offer on Linux. Using the 1.x versions would work, I expect. No reason to believe we couldn't restore support for mono on Linux in the 2.x line.

**Comment by mcmillab** [comment]
I'm using 2.0.147, the latest I believe.
I'll try 1.* and let you know how I get on.
