### ISSUE TITLE
iOS Linker removes support for PCLCrypto.SymmetricKeyAlgorithmProvider.GetAlgorithm

### ISSUE THREAD

**Issue by donaghy** [AArnott/PCLCrypto#218]
When building a MAUI project targeting iOS with MtouchLink = SdkOnly we are seeing the error "Speficied method is not supported" for the execution of PCLCrypto.SymmetricKeyAlgorithmProvider.GetAlgorithm(). When we set the MtouchLink option to None it works fine.

We dont see this issue in our Android release builds of the same project.

Note i raised this issue originally against MAUI but it was investigated and they believe the issue lays with the PCLCrypto library and that it is not trimmer safe. The full detail of the original error and a detailed description of what they believe to be the source of the problem can be found here:
[https://github.com/dotnet/maui/issues/20583]()

**Comment by AArnott** [comment]
PCLCrypto hasn't been developed for years -- long before trimmers were even a thing.
It was written when the .NET runtime that shipped across mobile platforms lacked the crypto that .NET Framework had. But that hole has long since been filled, and I would suggest you switch from PCLCrypto to the standard .NET APIs.

If that doesn't work for you, I'm curious what unique thing PCLCrypto offers that is still useful.

**Comment by donaghy** [comment]
I'll hold my hands up on that one, i took the path of least resistance and used the company shared toolkit without asking any questions about it! I'll roll up my sleeves and take a look at migrating to the new .Net APIs.

Thanks for update.

**Comment by donaghy** [comment]
.
