### ISSUE TITLE
 CryptographicEngine.Sign not implemented on WP8 ?

### ISSUE THREAD

**Issue by cmorgado** [AArnott/PCLCrypto#46]
I'm doing this code and getting an not implemented exception on the sign :S 
Any though?

    var mac = MacAlgorithmProvider.OpenAlgorithm(MacAlgorithm.HmacSha512);
            var keyMaterial = CryptographicBuffer.ConvertStringToBinary(hashKey, Encoding.UTF8);
            var cryptoKey = mac.CreateKey(keyMaterial);
            var hash = CryptographicEngine.Sign(cryptoKey, CryptographicBuffer.ConvertStringToBinary(stringToSign, Encoding.UTF8));
           return  CryptographicBuffer.EncodeToHexString(hash).ToUpper();

**Comment by AArnott** [comment]
What is the exception message? Does it talk about you using a reference assembly?
Can you include the exception callstack as well?

**Comment by cmorgado** [comment]
I just get

Exception thrown: 'System.NotSupportedException' in PCLCrypto.DLL
Exception thrown: 'System.NotSupportedException' in mscorlib.ni.dll

**Comment by AArnott** [comment]
Ah, so it's not a `NotImplementedException` as you said earlier. Good to know. 
Most likely WP8 doesn't support HmacSha512 signing. If you find out otherwise, please let me know. Otherwise, there's nothing PCLCrypto can do for you here as PCLCrypto only invokes platform crypto that already exists in the platform.
wpa81 should allow it though, I'm pretty sure.
