### ISSUE TITLE
ExportParameters produces arrays with an extra byte for leading zero on Desktop and WinRT (making interop with other crypto libraries difficult)

### ISSUE THREAD

**Issue by phofman** [AArnott/PCLCrypto#59]
Hi,

Maybe you could help me to explain my findings ;) - when I tried following code in my Windows Store 8.1 and Windows desktop .NET 4.5 application they both get some invalid lengths:

```csharp
var provider = WinRTCrypto.AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);
var rsaKey = provider.CreateKeyPair(1024);
publicKey = rsaKey.ExportParameters(false);
privateKey = rsaKey.ExportParameters(true);
```

More precisely:
 - on Windows Runtime - it gets 129 long instead of 128 for Modulus. Similarly P, Q and DQ are 65 instead of 64. For each of them first value is always '0', what is pretty strange.
 - on Windows Desktop - it's even more crazy; `publicKey.Modulus` is 129, while `privateKey.Modulus` is 128 and they also differ in heaving this leading '0' value.

Generally I am unable to encrypt/decrypt anything with it and skipping those '0' bytes doesn't seem right to me ;)

**Comment by phofman** [comment]
One more detail. Encryption/decryption itself works fine. I was just sending 'modulus' at some point inside the message to server and this leading-zero caused broken further communication. This way or another I still believe 64/128 lengths should be returned.

Temporary I started to use following patch and didn't notice any further side-effects:

```csharp
if (publicKey.Modulus[0] == 0 && publicKey.Modulus.Length == 129)
{
  publicKey.Modulus = publicKey.Modulus.Skip(1).ToArray();
  privateKey.Modulus = publicKey.Modulus;
 }

 if (privateKey.DP[0] == 0 && privateKey.DP.Length == 65)
 {
   privateKey.DQ = privateKey.DQ.Skip(1).ToArray();
   privateKey.P = privateKey.P.Skip(1).ToArray();
   privateKey.Q = privateKey.Q.Skip(1).ToArray();
 }
```

Thanks.

**Comment by AArnott** [comment]
What version of PCLCrypto are you using?
The leading 0 bit you're seeing is insurance that the number doesn't appear to be negative (since a leading zero signifies that). Negative numbers can cause issues for some crypto implementations. 
In recent versions of PCLCrypto we've revised how these leading zeros are handled to improve interoperability with iOS, thus the question as to which version you're using.

Also: as you say encryption works fine with or without these zeros, what if you used PCLCrypto on the server side as well? Would that resolve the issue?

**Comment by phofman** [comment]
I am using most recent NuGet package in Visual Studio 2015:

```xml
  <package id="PCLCrypto" version="1.0.86" targetFramework="portable45-net45+win8+wpa81" />
 ```
Yes, I do understand the problems with negatives (BigInteger and requirement of having leading zero). But maybe I am wrong, so please correct me, this should be handled by the library internally, right? Exporting doesn't produce a number here, but an array of bytes, so when doing export, I did expect a result to match the response received previously from platform's `RSACryptoServiceProvider` on Windows desktop.

If it's not possible to remove this leading zero due to iOS interoperability, then that's probably fine. Could you just confirm that my "quick patch" is the recommended approach to remove leading zero (maybe I should remove check for expected length) ? I have rather small influence on server-side and I it's not written in C#, so can't be changed that quickly ;)

Most of all - having updated documentation would be much appreciated (probably in `ExportParameters()` function or in `RSAParameters` xml-doc) ?

Thanks.

**Comment by AArnott** [comment]
Yes, it's based on the implementation, but if iOS's native platform exports keys made up of varying lengths in the arrays, it is something one has to deal with anyway if some platforms can handle it and some can't. PCLCrypto is gradually moving away from `RSACryptoServiceProvider` in the yet-to-be-released version, BTW, because of limitations it imposes that are not shared by other platforms. Instead, we're invoking directly to the Win32 BCrypt library (which .NET uses internally at least in some cases). PCLCrypto doesn't guarantee natural interoperability with all native platform crypto (indeed, it cannot, since the contracts between them are loose or non-existent). But PCLCrypto does endeavor to interop with itself, and with the *defined* key formats. For example, instead of using `ExportParameters`, you can and probably should use the `Export` and `ExportPublicKey` methods, which allows you to specify the key blob format, which is defined in RFCs. For example, if you specify the Capi format, you'll get the array lengths you expect because CAPI defines them that way -- although if your key is generated on iOS it will simply throw an exception because iOS keys simply do not fit in the CAPI spec -- thus CAPI is deprecated and I recommend against it in favor of a better format like Pkcs1, which includes array lengths with each array allowing more flexibility. 

Regardless, I'm happy to keep this issue active to track that `RSAParameters` should ideally not include leading zeros when doing so would prevent the array sizes from meeting the CAPI norms. It couldn't be a guarantee (again, in the case of iOS keys at least) but I suspect it would unblock you.

**Comment by phofman** [comment]
Great, thanks a lot!
