### ISSUE TITLE
Can't install package into a .NET Core project

### ISSUE THREAD

**Issue by scottdorman** [AArnott/PCLCrypto#64]
I'm using PCLCrypto in a current PCL targeting .NETPortable,Version=v4.0,Profile=Profile328 without any problems. When I try to "upgrade" this project to a .NET Core project (using project.json), I get the following error:

```
1>project.json(13,18,13,18): .NET Portable Subset (.NET Framework 4, Silverlight 5, Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8) error NU1002: The dependency PCLCrypto 1.0.86 in project DnxTest does not support framework .NETPortable,Version=v4.0,Profile=Profile328.
```

My project.json file looks like this:

```
{
  "dependencies": {
    "PCLCrypto": "1.0.86"
  },
  "frameworks": {
    ".NETPortable,Version=v4.0,Profile=Profile328": {
      "frameworkAssemblies": {
        "mscorlib": { },
        "System": { },
        "System.Core": { },
        "System.Net": { },
        "System.Runtime.Serialization": { }
      },
      "dependencies": {
      }
    }
  }
}
```

**Comment by scottdorman** [comment]
Incidentally, I'm not sure if this is a PCLCrypto issue or a .NET Core issue. PCLCrypto has a dependency on Validation, which installs just fine into the project.

**Comment by AArnott** [comment]
PCLCrypto is deprecating support for .NET 4.0. I don't recall exactly which version removes support for it (it may even be that all nuget.org published packages still support it). But just FYI.

**Comment by scottdorman** [comment]
Is there any particular reason for dropping .NET 4.0? As a side note, I tried specifying version 0.5.x explicitly, which I know had/has support for .NET 4.0 and it still didn't want to install.

From my original packages.config:

```
<packages> 
7   <package id="PCLCrypto" version="0.5.1.14165" targetFramework="portable-net40+sl50+win+wpa81+wp80" /> 
8   <package id="Validation" version="2.0.4.14103" targetFramework="portable-net40+sl50+win+wpa81+wp80" /> 
9 </packages> 
```

Dropping support for .NET 4.0 means that everybody using it will also have to drop support for that platform. In my case, I'm using it in another open source library that I want to have as broadly available as possible, so either I'll have to drop PCLCrypto or drop support for .NET 4.0.

**Comment by onovotny** [comment]
@scottdorman if you didn't already know, .NET 4-.NET 4.5.1 have already exited any support from Microsoft. That means when the next security vulnerability is discovered, only .NET 4.5.2 and higher will be patched. No one should be using .NET 4-4.5.1 anymore as it's dangerous.

**Comment by AArnott** [comment]
Good point, @onovotny 
@scottdorman The compelling reason for PCLCrypto (and any other PCL) to drop net40 support is that if you target net40, your assembly references mscorlib, which means it won't work on modern platforms such as Win8, WPA81, dnx, CoreCLR, etc. net45 and above will compile against "System.Runtime" and other facade assemblies so they were everywhere (as far back as .NET 4.5 anyway). PCLCrypto has previously bridged this gap by compiling twice, once for each .NET version target. However it was getting to be a major burden to target 5+ platforms (iOS, Android, WP*,...) *times 2* (net40 and net45) where applicable. The older versions of PCLCrypto that support net40 of course are still available (I think it goes as far as 1.0.x). And that branch can still be serviced if necessary. But some of the major replumbing work going into v.next is expected to be net45+ only. 
Of course it's open source, so if you want to bring support back to it, you can fork it and we *might* even accept a PR, but because the cost is mostly in the maintenance rather than just the conversion, I won't promise anything.

Yes, I'm split on it. PCLCrypto is mostly there for exactly the broad reach that isn't found any other way for crypto APIs. But SL5, net40, etc. simply isn't a relevant enough set of targets, as @onovotny points out, to justify the cost for my very limited time.

**Comment by scottdorman** [comment]
@onovotny That being said, we all know that there are still a ton of projects out there targeting frameworks earlier than .NET 4.5.2, including people who still have to work in .NET 3.0. 

@AArnott Thanks for the explanation. To be clear, it wasn't meant as a criticism. As for relevance, I do see .NET 4.0 as still being relevant; SL5 not so much though. For my purposes, the only thing I'm actually using out of PCLCrypto is this:
```
byte[] buffer = new byte[16];
PCLCrypto.NetFxCrypto.RandomNumberGenerator.GetBytes(buffer);
```
I might be able to just pull that code in directly as source rather than the entire library, which would solve my issue. 

I do hear what you're saying though about the broad reach. There still (at least as far as I know) any good crypto libraries for PCLs, especially for those targeting older frameworks. That burden is why my own library currently only supports the one PCL profile. Then again, I'm not doing anything that requires platform specific versions either, so the burden is a lot smaller.

**Comment by scottdorman** [comment]
So I changed my project so it's targeting `".NETPortable,Version=v4.5,Profile=Profile259"`, which is the same as what PCLCrypto is targeting and I still get the same error. (The only difference is the name of the PCL profile.)

**Comment by AArnott** [comment]
@scottdorman What project is this, BTW? 
If you just want the RNG, you should have no problem sticking with the v1.0 versions as RNG is very basic. But ya, we need it to at least install into your project.  :)

And ya, if neither of those profiles work for you, there's something odd going on. If this is an open source project, can you point me to it, and a commit that repros the problem? Otherwise, I guess check that your project.json and your PCL project file itself both agree on the portable profile as one thing I can think of.

**Comment by scottdorman** [comment]
@AArnott The commit is at https://github.com/scottdorman/cadru/commit/117b042ec9eae7cea569a5b7b9593ca057231a93 and a direct link to the folder tree with the project having problems is https://github.com/scottdorman/cadru/tree/117b042ec9eae7cea569a5b7b9593ca057231a93/src/Cadru.Core

I have checked that the PCL profile is the same between both projects and as far as I can tell, they are. The part that I don't get is that when I change the project.json to target the same framework as PCLCrypto (by just copying/pasting the TFM from your project into mine), I still get the same error.

**Comment by AArnott** [comment]
Fascinating. I just confirmed that profile328 is what pclcrypto itself builds with. I can repro the same problem on my machine with your code. The nupkg for PCLCrypto 1.0.86 looks correct, albeit not in the new format nuget likes to see (with dotnet folders and what-not). 

I'm going to guess that sometime after PCLCrypto was published, someone added a new platform to profile328 such that unless it's listed in the nupkg as a supported platform that it makes it incompatible. 

I filed a bug against nuget, shown above.

**Comment by scottdorman** [comment]
Thanks for confirming everything and filing the bug with NuGet. I'm glad this doesn't seem to be an issue with PCLCrypto or my code. :) Hopefully this gets fixed soon. Until then it looks like I won't be able to add support for .NET Core.

**Comment by AArnott** [comment]
Tip: What if you don't use xproj? Can you use csproj instead? That can target .NET Core as well, and that has a lot more NuGet stability.

**Comment by scottdorman** [comment]
Yes, that's an option although not one I want to use unless it's the only option. This project is just one of 5, with several more in process (plus test projects for each of those), so that's going to result in a lot of projects.

**Comment by AArnott** [comment]
Do you multi-target in your xproj? That's where it shines, I guess. But I find that it lacks too many features to be useful to me at present. And if you don't multi-target, csproj works great, IMO.

**Comment by scottdorman** [comment]
Yes, I was planning on multi-targeting in the xproj. It does lack a lot of features though. At least, there are a lot of things it supports that the tooling hasn't caught up to yet.

**Comment by AArnott** [comment]
It sounds like the linked issue is the correct one to track this, so I'll close this one.

For the sound of the linked issue, it seems that .NET Core projects can install PCLCrypto -- it's just xproj that lacks full support.
