### ISSUE TITLE
Aes Gcm Authenticated Encyption

### ISSUE THREAD

**Issue by globeport** [AArnott/PCLCrypto#90]
Am I right in thinking that there is not yet support for Aes Gcm?

Thanks,
Stuart

**Comment by AArnott** [comment]
Correct. Authenticated block modes are not yet supported.

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
