### ISSUE TITLE
CryptoStream with streamReader.ReadToEndAsync() not working on iOS 

### ISSUE THREAD

**Issue by gugavaro** [AArnott/PCLCrypto#93]
When I try to decrypt my data using CryptoStream and ReadToEndAsync on iOS, the call hangs, it works fine on other platforms.

``` csharp
using (var memoryStream = new MemoryStream(encryptedContent))
{
    using (var cryptoStream = new CryptoStream(memoryStream, decryptor, CryptoStreamMode.Read))
    {
        using (var streamReader = new StreamReader(cryptoStream))
        {
            var decryptedData = await streamReader.ReadToEndAsync();
            return decryptedData;
        }
    }
}
```

**Comment by asfend** [comment]
Share your whole code with me ...

**Comment by asfend** [comment]
And which encryption algorithms you're using ?

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
